name: "Setup Go"
description: "Setup Go environment with caching"
inputs:
  go-version-file:
    description: "Path to go.mod file"
    required: false
    default: "go.mod"
  cache-dependency-path:
    description: "Path to go.sum for cache key"
    required: false
    default: "go.sum"
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: ${{ inputs.go-version-file }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
