name: "Build Go Binary"
description: "Build Go binary for all platforms (amd64 and arm64)"
inputs:
  binary-name:
    description: "Name of the binary to build"
    required: true
  source-path:
    description: "Source path to build (e.g., ./cmd/controller)"
    required: true
  generate-code:
    description: "Whether to generate code first (for controller)"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Generate code
      if: inputs.generate-code == 'true'
      shell: bash
      run: |
        go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.19.0
        controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."

    - name: Build Go binaries for all platforms
      shell: bash
      run: |
        mkdir -p bin
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -trimpath -ldflags="-w -s" \
          -o bin/${{ inputs.binary-name }}-amd64 ${{ inputs.source-path }}
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 \
          go build -trimpath -ldflags="-w -s" \
          -o bin/${{ inputs.binary-name }}-arm64 ${{ inputs.source-path }}
        ls -lh bin/
