name: Release Drafter

on:
  push:
    branches:
      - main
      # Uncomment to enable pre-release drafting from develop/beta branches
      # - develop
      # - beta

permissions:
  contents: write
  pull-requests: write

jobs:
  update-release-draft-main:
    name: Update Release Draft (Main)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Uncomment to enable pre-release drafting from develop branch
  # update-release-draft-develop:
  #   name: Update Release Draft (Develop)
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/develop'
  #   steps:
  #     - uses: release-drafter/release-drafter@v6
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         config-name: release-drafter-develop.yml
